version: '3.9'

services:
  db:
    image: postgres
    container_name: db-mysite
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mysite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web-server:
    build: .
    container_name: web-server-mysite
    command: bash -c 'chmod +x /code/start.sh; /code/start.sh'
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
